import { useState } from 'react';
import { Brain, ChevronDown, Lightbulb } from 'lucide-react';
import type { EditPlan } from '../types';

interface Props {
  plan: EditPlan;
}

export default function AIReasoningPanel({ plan }: Props) {
  const [expanded, setExpanded] = useState(false);

  if (!plan.ai_summary && !plan.ai_reasoning) return null;

  return (
    <div className="panel overflow-hidden">
      <button
        className="w-full flex items-center justify-between p-4 hover:bg-film-dark/50 transition-colors"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-center gap-2">
          <Brain size={15} className="text-film-blue" />
          <span className="text-sm font-semibold">AI Edit Reasoning</span>
        </div>
        <ChevronDown size={16} className={`text-gray-400 transition-transform ${expanded ? 'rotate-180' : ''}`} />
      </button>

      {expanded && (
        <div className="px-4 pb-4 space-y-3 border-t border-film-border pt-3">
          {plan.ai_summary && (
            <div className="flex items-start gap-2">
              <Lightbulb size={13} className="text-film-accent mt-0.5 flex-shrink-0" />
              <p className="text-sm text-gray-300">{plan.ai_summary}</p>
            </div>
          )}
          {plan.ai_reasoning && (
            <div className="bg-film-dark rounded-lg p-3">
              <p className="text-xs text-gray-400 leading-relaxed whitespace-pre-wrap">{plan.ai_reasoning}</p>
            </div>
          )}
          <div className="flex items-center gap-4 text-xs text-gray-500">
            <span>{plan.decisions.length} edit decisions</span>
            <span>·</span>
            <span>Generated by Claude Opus 4.6</span>
          </div>
        </div>
      )}
    </div>
  );
}
